const CONFIG = {
    GEMINI_API_KEY: 'AIzaSyAmbODIVwtR6IQVYhtDGPDXEkJ7_tiO1M8',
    EMAILJS_SERVICE_ID: 'service_osplabt',
    EMAILJS_TEMPLATE_ID: 'template_gp8y77k',
    EMAILJS_TRACKING_TEMPLATE_ID: 'template_zgz0g1c',
    EMAILJS_PUBLIC_KEY: 'YOUR_EMAILJS_PUBLIC_KEY_HERE'
};
